### ISSUE TITLE
Partnersuche

### ISSUE THREAD

**Issue by barning** [Bremenhack/Orga#10]
Wir benötigen auch dieses Jahr Partner, die uns mit Know-How und Material unterstützen.
Partner vom letzten Jahr waren:
- [Hackerspace Bremen](https://www.hackerspace-bremen.de/)
- [Fablab Bremen](http://www.fablab-bremen.org/)

**Comment by barning** [comment]
Der Hackerspace hat seine Unterstützung zugesagt.

**Comment by barning** [comment]
Fablab angefragt

**Comment by manasse91** [comment]
sparkasse angefragt

**Comment by barning** [comment]
Brennerei angefragt
Besuch am 7.6.2016

**Comment by manasse91** [comment]
damit nix doppelt verschickt wird: ich frage conrad in habenhausen

**Comment by barning** [comment]
7meter17 hat gefragt ob sie Sponsor sein können. Betrag wird noch abgesprochen.

**Comment by barning** [comment]
Bremer Maker sind Partner : http://bremer-maker.de/
