### ISSUE TITLE
Bei Rundmails nicht alle Addressaten sichtbar ins to:-Feld 

### ISSUE THREAD

**Issue by dantz** [Bremenhack/Orga#5]
Ich würde es bevorzugen, wenn die E-Mail-Adressen nicht immer für alle sichtbar sind und auch Antworten dann nicht aus versehen an alle gehen können.

**Comment by barning** [comment]
Werden wir dran denken @dantz 
/cc @erotte

**Comment by erotte** [comment]
Jetzt ist es eh zu spät. Ja, ich wars, ich habs versehentlich ins to-Feld gepastet, sorry. Übrigens nicht immer, sondern bei der letzten Mail. Ich hoffe, es ist nichts schlimmes passiert. :scream:  Immerhin habe ich daran gedacht, eine Reply-To-Adresse angegeben, so dass die Antworten hoffentlich nicht an alle zurück gehen.

Während der Veranstaltung wurde übrigens der Wunsch geäussert, den Teilnehmer alle Mailadressen zur Verfügung zu stellen. Eine Lösung dafür wäre eine Google Group, aber das ist doch irgendwie alles :hankey: .

Kennt vielleicht jemand eine einfache Alternative zur Mailingliste? (Nein, bitte nicht Mailman, das ist auch :hankey: )

**Comment by barning** [comment]
Naja die einfache Alternative wäre Slack…
Ich bin kein Freund von Mailinglisten oder Verteilern

**Comment by erotte** [comment]
Ich auch nicht, aber Slack benutzen nur Leute, die Slack benutzen!

**Comment by barning** [comment]
Mailchimp-LInk wurde auf die Webseite gesetzt. Das Problem sollte sich dadurch besser beheben lassen.
