### ISSUE TITLE
Gestaltung des BremenHack

### ISSUE THREAD

**Issue by barning** [Bremenhack/Orga#6]
Gestaltung könnte (sollte) überarbeitet werden um freundlich und nicht zu bootstrappig auszusehen.
Inspiration:
- http://beyondtellerrand.com/
- http://2015.jsconf.eu/
- http://2015.cssconf.eu/
- http://2015.dconstruct.org/
- http://push-conference.com/2015/
- https://2015.mozillafestival.org/
- http://2015.front-trends.com/
- http://2015.tvhackday.com/
- http://www.oktoberhackfest.com/

Wir sollten vielleicht gucken ob wir auch Videomaterial nutzen können.

**Comment by barning** [comment]
Eventuell Uberspace als Sponsor für die neue Seite?

**Comment by barning** [comment]
Der aktuelle Stand der Wordpress Seite.

![bremenhack](https://cloud.githubusercontent.com/assets/2111657/11351234/b8be07d2-9235-11e5-8061-1130fa093441.png)

**Comment by deny-todorova** [comment]
Sehr sehr schön! ^_^

**Comment by barning** [comment]
Die neue Seite ist online: http://bremenhack.de/
