### ISSUE TITLE
Nachbearbeitung - Präsentationen

### ISSUE THREAD

**Issue by barning** [Bremenhack/Orga#7]
Es sollen Vorträge gehalten werden um anhand des BremenHack 2015 zu erklären was der BremenHack ausmacht und warum es gut ist Sponsor/Teilnehmer zu werden.

**Comment by barning** [comment]
Der @erotte kümmert sich um ein Pecha Kucha.

**Comment by barning** [comment]
Ich kümmere mich um einen Vortrag beim Webmontag

**Comment by barning** [comment]
"Webmontag"-Keynote wurde zu "Vortrag"-Keynote umbenannt. Es fehlt noch eine Roadmap, die den Ablauf des Wochenendes erklärt.
Macht es Sinn den Vortrag in [reveal.js](http://lab.hakim.se/reveal-js/#/) umzugießen?

**Comment by erotte** [comment]
Supi! 
Ich komme mit Keynote gut zurecht und sehe keinen Bedarf, dass  auf reveal.js umzubauen.
