### ISSUE TITLE
Locationsuche

### ISSUE THREAD

**Issue by barning** [Bremenhack/Orga#8]
Wir sollten schauen, welche Locations für den BremenHack überhaupt in Bremen zur Verfügung stehen könnten.

**Comment by barning** [comment]
Ich habe das [noon](http://noon.jetzt/) und den [Karton](http://www.kartontage.de/) angefragt. Angebote stehen noch aus.

**Comment by manasse91** [comment]
wie sieht es mit institutionen aus? zB die HfK, das DFKI, die Uni oder so? Was muss alles vorhanden sein, um sich als location zu qualifizieren?

**Comment by barning** [comment]
Die Location sollte so wenig wie möglich an ein Büro erinnern. Lieber ein Café fürs Wochenende als einen typischen Arbeitsraum.

**Comment by barning** [comment]
Noon kommt wegen zeitlichen differenzen nicht in Frage

**Comment by barning** [comment]
Kulturküche angefragt: http://www.kulturkueche.org/
Warten auf Zusage und Angebot.
