### ISSUE TITLE
Sponsorensuche

### ISSUE THREAD

**Issue by barning** [Bremenhack/Orga#9]
Welche Sponsoren kommen für 2016 in Frage? Alte Sponsoren müssen wir fragen und neue Sponsoren sollten wir auftreiben.

**Comment by barning** [comment]
Ich habe Neusta angefragt

**Comment by manasse91** [comment]
ich frage die Sparkasse, fritz kola, hmmh, das DFKI und intel :)

**Comment by barning** [comment]
hmmh übernehme ich, weil ich da meine alte Chefin als Kontakt habe :)

**Comment by barning** [comment]
neusta hat zugesagt :+1:

**Comment by barning** [comment]
hmmh angefragt

**Comment by barning** [comment]
7meter17 hat gefragt ob sie Sponsor sein können. Betrag wird noch abgesprochen.

**Comment by barning** [comment]
7meter17 macht mit
